# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy UniPass wagmi-connector-demo

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Install Dependencies
        run: |
          npm i -g yarn
          yarn install
      - name: Build
        run: yarn build
        
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
